name: Backend CI workflow
on:
  push:
    paths:
      - 'backend/audio-service/**'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/audio-service/**'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/audio-service
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18.x
          cache-dependency-path: ./backend/audio-service/package-lock.json
      - run: npm ci
      - name: Build app
        run: npm run build

  deploy-container:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/audio-service
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - run: echo $YANDEX_AUTH_KEY | docker login --username json_key --password-stdin cr.yandex
        env:
          YANDEX_AUTH_KEY: ${{ secrets.YANDEX_AUTH_KEY }}
      - run: |
          echo "Packaging docker image ..."
          tag="$DOCKER_REGISTRY/banzai-audio-service:${{ github.sha	}}"
          docker build . -t $tag
          docker push $tag
        env:
          DOCKER_REGISTRY: cr.yandex/crp4ultpl6m2qegvp1s6
#      - name: Commit report
#        working-directory: k8s-apps/banzai-audio-service/
#        run: |
#          git pull
#          echo -e "image: \n  tag: ${{ github.sha }}" > values-production.yaml
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add values-production.yaml
#          git commit -m "bump backend version"
#          git push
