name: Frontend CI workflow
on:
  push:
    paths:
      - 'dashboard/**'
    branches:
      - main
  pull_request:
    paths:
      - 'dashboard/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dashboard
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18.x
          cache-dependency-path: ./dashboard/package-lock.json
      - run: npm ci
      - run: npm run build
        env:
          REACT_APP_API_URL: https://api.banzai-predict.site

      - run: zip -qq -r build.zip build

      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          path: ./dashboard/build.zip
          name: build.zip

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: build.zip
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq build.zip -d build
      # Set the credentials from repository settings/secrets
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net/
          AWS_S3_BUCKET: banzai-predict.site
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build/build'      # optional: defaults to entire repository