name: Infra CI workflow
on:
  push:
    paths:
      - 'infra/**'
    branches:
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      # Download previously shared build
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      # Copy the files from build folder to the S3 bucket
      - name: Save key file
        env:
          YANDEX_AUTH_KEY: ${{ secrets.YANDEX_AUTH_KEY }}
        run: echo $YANDEX_AUTH_KEY > key.json
      # Copy the files from build folder to the S3 bucket
      - name: Init terraform
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
      - name: Plan terraform
        env:
          TF_VAR_app_version: ${{ github.sha }}
        run: terraform plan
      - name: Deploy terraform
        env:
          TF_VAR_app_version: ${{ github.sha }}
        run: terraform apply -auto-approve